title: Mapping Loss — Libraries and Lives in Palestine
#logo: docs/assets/img/olive-branch-front-2.jpg
description: This project visualizes the destruction of Palestinian libraries alongside the lives lost on or around the same dates, creating a powerful data-driven narrative that links cultural annihilation with human tragedy.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
